title: Optimizing Attribute Selection for 3D Model Popularity Prediction using Clustering and Machine Learning
description: Kamyar Fatemifar, Suchismitaa Chakraverty, Joseph Hardin, Abhishek Misra, Max Pan
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
